---
title: "R Notebook"
output: html_notebook
---

Connect to database:
```{r}

library("RSQLite")
library(tidyr)
library(dplyr)
library(modelr)
library(caret)
db.conn <- dbConnect(RSQLite::SQLite(), dbname="worldHealth_v2.db")

```

```{r}

health<- dbGetQuery(db.conn,   
"SELECT c.Cause, ye.Year, l.Location, y.Data FROM yearlyGBD AS y
JOIN locations AS l ON y.Location = l.lid
JOIN causes AS c ON y.Cause = c.cid
JOIN years AS ye ON y.Year = ye.yid")

colnames(health)[3] = "Country"
colnames(health)[4] = "Death_Percent"
health <- health[order(health$Year, health$Country, health$Cause),]

```

```{r diabetes deaths map }

world_map <- map_data("world")
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill="lightgray", colour = "white")

data.countries <- rownames(health$Country)

countries.maps <- map_data("world", region = data.countries)

region.lab.data <- countries.maps %>%
  group_by(region) %>%
  summarise(long = mean(long), lat = mean(lat))


ggplot(countries.maps, aes(x = long, y = lat)) +
  geom_polygon(aes(group = group, fill = data.countries)) +
  geom_text(aes(label = region), data = region.lab.data,  size = 3, hjust = 0.5) 

```

```{r}

economic<- dbGetQuery(db.conn,   
"SELECT s.Series, ye.Year, l.Location, y.Data FROM yearlyWB AS y
JOIN locations AS l ON y.Location = l.lid
JOIN series AS s ON y.Series = s.sid
JOIN years AS ye ON y.Year = ye.yid")

colnames(economic)[3] = "Country"

economic <- economic %>% 
  group_by(Year, Country, Series) %>% 
  slice(1) %>% 
  pivot_wider(names_from = Series, values_from = Data)


economic <- economic[order(economic$Country, economic$Year),]

cols <- colnames(economic)[-1:-2]
economic[ , cols] <- apply(economic[ , cols], 2, function(x) as.numeric(as.character(x)))

colnames(economic)[3] <- "Access_to_clean_fuels_and_technologies_for_cooking"
colnames(economic)[4] <- "Access_to_electricity"
colnames(economic)[5] <- "Agricultural_land_percent_of_land_area"
colnames(economic)[6] <- "Agricultural_land_sq_km"
colnames(economic)[7] <- "CO2_emissions_kg"
colnames(economic)[8] <- "CO2_emissions_kt"
colnames(economic)[9] <- "CO2_emissions_metric_tons_per_capita"
colnames(economic)[10] <- "Current_health_expenditure_percent_of_GDP"
colnames(economic)[11] <- "Current_health_expenditure_per_capita"
colnames(economic)[12] <- "Domestic_general_government_health_expenditure_percent_of_current_health_expenditure"
colnames(economic)[13] <- "Domestic_general_government_health_expenditure_percent_of_GDP"
colnames(economic)[14] <- "Domestic_general_government_health_expenditure_percent_of_general_government_expenditure"
colnames(economic)[15] <- "Domestic_general_government_health_expenditure_per_capita"
colnames(economic)[16] <- "Domestic_private_health_expenditure_percent_of_current_health_expenditure"
colnames(economic)[17] <- "Domestic_private_health_expenditure_per_capita"
colnames(economic)[18] <- "Domestic_private_health_expenditure_per_capita_PPP"
colnames(economic)[19] <- "Fertility_rate"
colnames(economic)[20] <- "Fixed_telephone_subscriptions"
colnames(economic)[21] <- "Fixed_telephone_subscriptions_per_100_people"
colnames(economic)[22] <- "Forest_area_percent_of_land_area"
colnames(economic)[23] <- "GDP_constant_2015_US"
colnames(economic)[24] <- "GDP_current_US"
colnames(economic)[25] <- "GDP_growth_annual"
colnames(economic)[26] <- "GDP_per_capita_constant_2015_US"
colnames(economic)[27] <- "GDP_per_capita_current_US"
colnames(economic)[28] <- "GDP_per_capita_growth_annual"
colnames(economic)[29] <- "Individuals_using_the_Internet_percent_of_population"
colnames(economic)[30] <- "Land_area_sq_km"
colnames(economic)[31] <- "Mobile_cellular_subscriptions_per_100_people"
colnames(economic)[32] <- "Nitrous_oxide_emissions"
colnames(economic)[33] <- "Out_of_pocket_expenditure_percent_of_current_health_expenditure"
colnames(economic)[34] <- "Out_of_pocket_expenditure_per_capita_current_US"
colnames(economic)[35] <- "People_using_atleast_basic_drinking_water_services_percent_of_population"
colnames(economic)[36] <- "People_using_atleast_basic_sanitation_services_percent_of_population"
colnames(economic)[37] <- "Permanent_cropland_percent_of_land_area"
colnames(economic)[38] <- "Population_density_people_per_sq_km_of_land_area"
colnames(economic)[39] <- "Population_growth_annual"
colnames(economic)[40] <- "Proportion_of_seats_held_by_women_in_parliaments"
colnames(economic)[41] <- "Total_greenhouse_gas_emissions_kt"

```

```{r}

# Diabetes and kidney diseases 2015
diabetes_2019 <- merge(
  health %>% 
    filter(Year==2019 & Cause=="Diabetes and kidney diseases"), 
  economic %>% 
    filter(Year==2019), 
  by = c("Year", "Country")) %>% 
  relocate(Death_Percent, .after = last_col())
diabetes_2019 <- diabetes_2019[,!names(diabetes_2019) %in% 
                                       c("Year", "Cause")]
columns <- colnames(diabetes_2019)
columns <- columns[-1]
diabetes_2019 <- diabetes_2019 %>%
  group_by(Country) %>%
  mutate_at(columns, ~ifelse(is.na(.), mean(., na.rm = TRUE), .))


# Diabetes and kidney diseases 2015
diabetes_2015 <- merge(
  health %>% 
    filter(Year == 2015 & Cause == "Diabetes and kidney diseases"), 
  economic %>% 
    filter(Year == 2015), 
  by = c("Year", "Country")) %>% 
  relocate(Death_Percent, .after = last_col())
diabetes_2015 <- diabetes_2015[,!names(diabetes_2015) %in% 
                                       c("Year", "Cause")]
columns <- colnames(diabetes_2015)
columns <- columns[-1]
diabetes_2015 <- diabetes_2015 %>%
  group_by(Country) %>%
  mutate_at(columns, ~ifelse(is.na(.), mean(., na.rm = TRUE), .))


# Diabetes and kidney diseases 2010
diabetes_2010 <- merge(
  health %>% 
    filter(Year == 2010 & Cause == "Diabetes and kidney diseases"), 
  economic %>% 
    filter(Year == 2010), 
  by = c("Year", "Country")) %>% 
  relocate(Death_Percent, .after = last_col())
diabetes_2010 <- diabetes_2010[,!names(diabetes_2010) %in% 
                                       c("Year", "Cause")]
columns <- colnames(diabetes_2010)
columns <- columns[-1]
diabetes_2010 <- diabetes_2010 %>%
  group_by(Country) %>%
  mutate_at(columns, ~ifelse(is.na(.), mean(., na.rm = TRUE), .))


# Diabetes and kidney diseases 2005
diabetes_2005 <- merge(
  health %>% 
    filter(Year == 2005 & Cause == "Diabetes and kidney diseases"), 
  economic %>% 
    filter(Year == 2005), 
  by = c("Year", "Country")) %>% 
  relocate(Death_Percent, .after = last_col())
diabetes_2005 <- diabetes_2005[,!names(diabetes_2005) %in% 
                                       c("Year", "Cause")]
columns <- colnames(diabetes_2005)
columns <- columns[-1]
diabetes_2005 <- diabetes_2005 %>%
  group_by(Country) %>%
  mutate_at(columns, ~ifelse(is.na(.), mean(., na.rm = TRUE), .))


# Diabetes and kidney diseases 2000
diabetes_2000 <- merge(
  health %>% 
    filter(Year == 2000 & Cause == "Diabetes and kidney diseases"), 
  economic %>% 
    filter(Year == 2000), 
  by = c("Year", "Country")) %>% 
  relocate(Death_Percent, .after = last_col())

diabetes_2000 <- diabetes_2000[,!names(diabetes_2000) %in% 
                                       c("Year", "Cause")]
columns <- colnames(diabetes_2000)
columns <- columns[-1]
diabetes_2000 <- diabetes_2000 %>%
  group_by(Country) %>%
  mutate_at(columns, ~ifelse(is.na(.), mean(., na.rm = TRUE), .))


```









```{r}

predictors <- c("People_using_atleast_basic_drinking_water_services_percent_of_population", 
           "Access_to_electricity", 
           "Proportion_of_seats_held_by_women_in_parliaments", 
           "Domestic_general_government_health_expenditure_per_capita",
           "Domestic_private_health_expenditure_per_capita",
           "Out_of_pocket_expenditure_per_capita_current_US",
           "Population_density_people_per_sq_km_of_land_area"
           )

# Initialize the list of selected predictors and the minimum RMSE
selected_predictors <- NULL
min_rmse <- Inf

# Loop through each predictor and add the one with the lowest RMSE to the model
for (i in 1:(length(predictors))) {
  
  # Initialize the list of candidate predictors
  candidate_predictors <- setdiff(predictors, selected_predictors)
  
  # Calculate the RMSE of each candidate predictor added to the selected predictors
  candidate_rmse <- sapply(candidate_predictors, function(predictor) {
    # Build a linear regression model using the selected predictors and the current candidate predictor
    formula <- paste("Death_Percent", paste(c(selected_predictors, predictor), collapse = " + "), sep = " ~ ")
    model <- lm(formula, data = diabetes_2015)
    
    # Calculate the RMSE of the model
    predictions <- predict(model, diabetes_2019)
    RMSE(predictions, diabetes_2019$Death_Percent)
  })
  
  # Find the candidate predictor with the lowest RMSE
  best_candidate_predictor <- candidate_predictors[which.min(candidate_rmse)]
  best_candidate_rmse <- candidate_rmse[which.min(candidate_rmse)]
  
  # Add the best candidate predictor to the list of selected predictors
  selected_predictors <- c(selected_predictors, best_candidate_predictor)
  
  # If the RMSE is lower than the current minimum, update the minimum
  if (best_candidate_rmse < min_rmse) {
      min_rmse <- best_candidate_rmse
  }
  
  print(best_candidate_rmse)
  print("---------------------")
}

# Print the selected predictors and the minimum RMSE
cat("Best predictors: ", selected_predictors, sep = "\n")
cat("Minimum RMSE: ", min_rmse, "\n")


```


